const bcrypt = require('bcryptjs');
const data = {
    users: [
        {
            name: 'Bing',
            email: 'admin@zk.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true
        },
        {
            name: 'Jon',
            email: 'jon@zk.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false
        },
    ], 
    products: [
        {
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            name: 'Nike Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Reebok Fit Shirt',
            category: 'shirts',
            image: '/images/p10.jpg',
            price: 139,
            countInStock: 18,
            brand: 'Adidas',
            rating: 6.7,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Mufty Shirt',
            category: 'Shirts',
            image: '/images/p7.jpg',
            price: 699,
            countInStock: 32,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Wrogn Shirt',
            category: 'Shirts',
            image: '/images/p8.jpg',
            price: 230,
            countInStock: 50,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Highlander Shirt',
            category: 'Shirts',
            image: '/images/p9.jpg',
            price: 144,
            countInStock: 12,
            brand: 'Adidas',
            rating: 2.3,
            numReviews: 15,
            description: 'low quality product',
        },
        {
            name: 'Raymond Shirt',
            category: 'Shirts',
            image: '/images/p11.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            name: 'Prter England Shirt',
            category: 'Shirts',
            image: '/images/p12.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};

module.exports = data;
